# Generated by Django 5.0.5 on 2024-07-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=255)),
                ("image", models.ImageField(upload_to="categories/%Y/%m/%d/")),
                ("is_mega", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
