# Generated by Django 5.0.5 on 2024-07-04 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.CharField(max_length=120)),
                ("more_description", models.TextField(blank=True, null=True)),
                ("additional_infos", models.TextField(blank=True, null=True)),
                ("stock", models.IntegerField()),
                ("sold_price", models.FloatField()),
                ("regular_price", models.FloatField()),
                ("brand", models.CharField(blank=True, max_length=60, null=True)),
                ("is_available", models.BooleanField()),
                ("is_best_seller", models.BooleanField()),
                ("is_new_arrival", models.BooleanField()),
                ("is_featured", models.BooleanField()),
                ("is_special_offer", models.BooleanField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("categories", models.ManyToManyField(to="shop.category")),
            ],
        ),
        migrations.AddField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="shop.product",
            ),
            preserve_default=False,
        ),
    ]
