# Generated by Django 5.0.5 on 2024-07-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_product_image_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=4)),
                ("taxe_rate", models.FloatField()),
                ("logo", models.ImageField(upload_to="settings/")),
                ("street", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=60)),
                ("state", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("copyright", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
