# Generated by Django 5.0.5 on 2024-07-05 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_social"),
    ]

    operations = []
